kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: expense
          key: course
    - name: author
      valuefrom:
        configMapKeyRef:
          name: expense
          key: author